<?php

namespace Database\Seeders;

use App\Models\Topic;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;

class TopicSeeder extends Seeder
{
    public function run(): void
    {
        $topics = $this->getTopics();

        foreach ($topics as $index => $topic) {
            Topic::updateOrCreate(
                ['slug' => $topic['slug']],
                array_merge($topic, ['sort_order' => $index + 1]),
            );
        }

        Cache::forget('topics:all');
    }

    private function getTopics(): array
    {
        return [
            // ==================== CORE TOPICS (26) ====================
            [
                'slug' => 'back-of-the-envelope-estimation',
                'title' => 'Back-of-the-Envelope Estimation',
                'category' => 'Estimation',
                'section' => 'core',
                'level' => 'Beginner',
                'hook_question' => "You're designing a system for Twitter. How would you estimate the storage needed per day if Twitter has 500 million tweets/day, each averaging 300 bytes of text? What about with images — say 10% of tweets have a 200KB image?",
                'description' => 'The art of making quick, rough calculations to evaluate system capacity, resource requirements, and feasibility before diving into detailed design.',
                'key_points' => json_encode(['Powers of 2', 'Latency numbers every engineer should know', 'QPS estimation', 'Storage estimation', 'Bandwidth estimation']),
            ],
            [
                'slug' => 'performance-vs-scalability',
                'title' => 'Performance vs Scalability',
                'category' => 'Performance & Scalability',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "Your web app handles 100 requests/second perfectly, but at 10,000 requests/second it crashes. Is this a performance problem or a scalability problem? What's the fundamental difference, and how would you address each?",
                'description' => 'Understanding the distinction between making a system fast (performance) and making it handle growth (scalability) is foundational to system design.',
                'key_points' => json_encode(['Vertical vs horizontal scaling', 'Performance optimization', 'Scalability patterns', 'Resource utilization', 'Bottleneck identification']),
            ],
            [
                'slug' => 'latency-vs-throughput',
                'title' => 'Latency vs Throughput',
                'category' => 'Performance & Scalability',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => 'A highway has 4 lanes and cars travel at 60mph. If you add 4 more lanes, does the latency change? Does the throughput change? How does this analogy apply to system design?',
                'description' => "Latency is how long a single request takes; throughput is how many requests you can handle. They're related but not the same, and optimizing one can hurt the other.",
                'key_points' => json_encode(['Response time vs bandwidth', 'P50/P95/P99 latencies', "Little's Law", 'Queueing theory basics', 'Latency-throughput tradeoffs']),
            ],
            [
                'slug' => 'dns-fundamentals',
                'title' => 'DNS Fundamentals',
                'category' => 'Domain Name System',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "When you type 'google.com' in your browser, at least 4 different DNS servers are involved before you get an IP address. Can you name them and explain the resolution chain? Why is DNS designed this way?",
                'description' => "DNS is the internet's phone book — translating human-readable domain names into IP addresses. It's a globally distributed, hierarchical system.",
                'key_points' => json_encode(['DNS hierarchy', 'Record types (A, AAAA, CNAME, MX, NS)', 'TTL and caching', 'DNS resolution flow', 'DNS as load balancing']),
            ],
            [
                'slug' => 'load-balancers-overview',
                'title' => 'Load Balancers Overview',
                'category' => 'Load Balancers',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "You have 5 servers behind a load balancer. One server is twice as powerful as the others. How would you ensure it handles proportionally more traffic? What happens when a server goes down — how does the LB know?",
                'description' => 'Load balancers distribute incoming traffic across multiple servers to ensure no single server becomes overwhelmed, improving availability and responsiveness.',
                'key_points' => json_encode(['L4 vs L7 load balancing', 'Health checks', 'Session persistence', 'Active-passive vs active-active', 'Hardware vs software LB']),
            ],
            [
                'slug' => 'load-balancing-algorithms',
                'title' => 'Load Balancing Algorithms',
                'category' => 'Load Balancers',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "Round-robin is simple — just go to the next server. But what if servers have different capacities, or some requests take 100x longer than others? Describe at least 3 load balancing algorithms and when you'd choose each.",
                'description' => 'Different load balancing algorithms suit different scenarios. Choosing the right one depends on your server fleet, request patterns, and session requirements.',
                'key_points' => json_encode(['Round Robin', 'Weighted Round Robin', 'Least Connections', 'IP Hash', 'Random with Two Choices']),
            ],
            [
                'slug' => 'rate-limiting',
                'title' => 'Rate Limiting',
                'category' => 'Load Balancers',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "Your API is being hit by a client making 10,000 requests per second. How would you implement rate limiting? What's the difference between token bucket and sliding window approaches? Which would you choose for an API gateway?",
                'description' => 'Rate limiting controls the rate of requests a client can make, protecting services from abuse, DDoS attacks, and ensuring fair usage.',
                'key_points' => json_encode(['Token bucket algorithm', 'Leaky bucket', 'Fixed window', 'Sliding window log', 'Sliding window counter']),
            ],
            [
                'slug' => 'caching-overview',
                'title' => 'Caching Overview',
                'category' => 'Caching Fundamentals',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "You're told to 'add caching' to speed up your application. But caching can actually make things WORSE in some cases. When does caching help, when does it hurt, and where in the stack would you place caches?",
                'description' => 'Caching stores copies of frequently accessed data in faster storage layers, dramatically reducing latency and database load when used correctly.',
                'key_points' => json_encode(['Cache hit vs miss', 'Cache layers (client, CDN, app, DB)', 'Cache warming', 'Thundering herd problem', 'Cache cost vs benefit']),
            ],
            [
                'slug' => 'cache-aside-lazy-loading',
                'title' => 'Cache Aside (Lazy Loading)',
                'category' => 'Caching Strategies',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => 'In cache-aside pattern, the application checks the cache first, then the database on a miss. But what happens when 1,000 requests simultaneously miss the cache for the same key? How would you solve this?',
                'description' => 'Cache-aside is the most common caching strategy where the application manages the cache explicitly — reading from cache first and populating it on misses.',
                'key_points' => json_encode(['Lazy population', 'Cache miss penalty', 'Stale data risk', 'Thundering herd mitigation', 'Best for read-heavy workloads']),
            ],
            [
                'slug' => 'write-through-cache',
                'title' => 'Write-Through Cache',
                'category' => 'Caching Strategies',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "Write-through ensures cache and database always have the same data by writing to both. But this means every write is slower. When would you accept this tradeoff? Compare it with write-behind (write-back) — what's the risk?",
                'description' => 'Write-through caching writes data to both the cache and database simultaneously, ensuring consistency at the cost of write latency.',
                'key_points' => json_encode(['Data consistency guarantee', 'Write latency penalty', 'Write-behind alternative', 'Durability tradeoffs', 'Hybrid approaches']),
            ],
            [
                'slug' => 'cache-invalidation',
                'title' => 'Cache Invalidation',
                'category' => 'Caching Strategies',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "Phil Karlton famously said there are only two hard things in CS: cache invalidation and naming things. Why is cache invalidation so hard? What happens when your cache says a product costs \$10 but the database says \$15?",
                'description' => 'Cache invalidation is the process of removing or updating stale data from the cache. Getting it wrong means serving incorrect data; getting it right is genuinely difficult.',
                'key_points' => json_encode(['TTL-based expiration', 'Event-driven invalidation', 'Purge vs ban', 'Invalidation propagation', 'Consistency vs freshness']),
            ],
            [
                'slug' => 'databases-overview',
                'title' => 'Databases Overview',
                'category' => 'Database Fundamentals',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "You're building an e-commerce platform. You need to store user profiles, product catalog, order history, shopping carts, and search indexes. Would you use one database for everything or different databases for different data? Why?",
                'description' => 'Choosing the right database is one of the most impactful decisions in system design. Different data models suit different access patterns and consistency requirements.',
                'key_points' => json_encode(['ACID properties', 'Relational vs non-relational', 'Polyglot persistence', 'Read vs write optimized', 'Indexing fundamentals']),
            ],
            [
                'slug' => 'sql-vs-nosql',
                'title' => 'SQL vs NoSQL',
                'category' => 'Database Fundamentals',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "A startup says 'We chose MongoDB because it scales better than PostgreSQL.' Is this reasoning correct? Under what circumstances would a relational database actually scale BETTER than a NoSQL database?",
                'description' => 'SQL databases provide structured schemas and ACID transactions; NoSQL databases offer flexibility and horizontal scalability. Neither is universally better.',
                'key_points' => json_encode(['Schema vs schemaless', 'ACID vs BASE', 'Joins and relationships', 'Horizontal scalability', 'Use case matching']),
            ],
            [
                'slug' => 'consistent-hashing',
                'title' => 'Consistent Hashing',
                'category' => 'CAP Theorem & Consistency',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "You have 5 cache servers and use 'hash(key) % 5' to pick which server stores each key. Now you add a 6th server. What percentage of keys need to move? How does consistent hashing reduce this to near-minimum?",
                'description' => 'Consistent hashing is a technique that minimizes key redistribution when nodes are added or removed, essential for distributed caches and databases.',
                'key_points' => json_encode(['Hash ring concept', 'Virtual nodes', 'Minimal disruption on scaling', 'Key distribution balance', 'Used in DynamoDB, Cassandra, CDNs']),
            ],
            [
                'slug' => 'cap-theorem',
                'title' => 'CAP Theorem',
                'category' => 'CAP Theorem & Consistency',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "The CAP theorem says you can only have 2 of 3: Consistency, Availability, Partition tolerance. But network partitions WILL happen. So are you really choosing between C and A? Give an example of when you'd choose each.",
                'description' => 'CAP theorem states that a distributed system can provide at most two of: Consistency, Availability, and Partition tolerance. Since partitions are inevitable, the real choice is between C and A during a partition.',
                'key_points' => json_encode(['Consistency = every read gets most recent write', 'Availability = every request gets a response', 'Partition tolerance = system works despite network failures', 'CP vs AP systems', 'PACELC extension']),
            ],
            [
                'slug' => 'availability-vs-consistency',
                'title' => 'Availability vs Consistency',
                'category' => 'CAP Theorem & Consistency',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "A banking system and a social media 'likes' counter both need to be distributed. One absolutely needs consistency, the other can tolerate inconsistency. Which is which, and what architectures would you use for each?",
                'description' => 'The tension between availability and consistency is at the heart of distributed systems design. Different applications have different requirements.',
                'key_points' => json_encode(['Strong consistency', 'Eventual consistency', 'Linearizability', 'Read-your-writes consistency', 'Business requirement alignment']),
            ],
            [
                'slug' => 'replication',
                'title' => 'Replication',
                'category' => 'Availability Patterns',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "You set up a primary database with 2 replicas. A write goes to the primary and the user immediately reads from a replica. They don't see their own write. What happened, and how would you fix it without sacrificing read scalability?",
                'description' => 'Replication copies data across multiple nodes for fault tolerance and read scalability. The challenge is keeping replicas consistent with the primary.',
                'key_points' => json_encode(['Leader-follower replication', 'Multi-leader replication', 'Leaderless replication', 'Synchronous vs asynchronous', 'Replication lag']),
            ],
            [
                'slug' => 'fail-over',
                'title' => 'Fail-Over',
                'category' => 'Availability Patterns',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "Your primary database server dies. You have a standby replica ready. But during the 30 seconds it takes to promote the replica, 500 write requests arrive. What happens to them? Compare active-passive vs active-active failover strategies.",
                'description' => 'Failover is the process of switching to a standby system when the primary fails. Quick, reliable failover is essential for high availability.',
                'key_points' => json_encode(['Active-passive failover', 'Active-active failover', 'Failover detection', 'Split-brain problem', 'Failover time (RTO)']),
            ],
            [
                'slug' => 'availability-in-numbers',
                'title' => 'Availability in Numbers',
                'category' => 'Availability Patterns',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "Your SLA promises 99.99% uptime. How many minutes of downtime per year is that? If your system has 3 components in series, each at 99.9% availability, what's the total system availability? What if they're in parallel?",
                'description' => "Availability is measured in 'nines' and understanding the math behind it is crucial for setting realistic SLAs and designing redundant systems.",
                'key_points' => json_encode(['Nines of availability', 'Serial vs parallel availability', 'SLA/SLO/SLI', 'MTBF and MTTR', 'Error budgets']),
            ],
            [
                'slug' => 'sharding',
                'title' => 'Sharding',
                'category' => 'RDBMS Patterns',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "Your database has 10TB of data and queries are getting slow. You decide to shard. How do you choose a shard key? What happens when you need to query across shards? What if one shard gets 80% of the traffic (hot shard)?",
                'description' => 'Sharding horizontally partitions data across multiple database instances, allowing a database to scale beyond the limits of a single machine.',
                'key_points' => json_encode(['Shard key selection', 'Range-based vs hash-based sharding', 'Cross-shard queries', 'Resharding challenges', 'Hot shard mitigation']),
            ],
            [
                'slug' => 'eventual-consistency',
                'title' => 'Eventual Consistency',
                'category' => 'Consistency Patterns',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "You update your profile picture on a social media app. Your friend in another country still sees the old picture for 5 seconds. Is this a bug? When is this acceptable, and what guarantees can you still provide?",
                'description' => 'Eventual consistency guarantees that if no new updates are made, all replicas will eventually converge to the same value. It trades immediate consistency for availability and performance.',
                'key_points' => json_encode(['Convergence guarantee', 'Conflict resolution', 'Read-your-writes consistency', 'Monotonic reads', 'Session consistency']),
            ],
            [
                'slug' => 'message-queues',
                'title' => 'Message Queues',
                'category' => 'Asynchronism Fundamentals',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "A user uploads a video that needs to be encoded into 5 different resolutions. Should you do this synchronously in the API request? If not, how would you design the async processing? What happens if the encoding worker crashes halfway through?",
                'description' => 'Message queues decouple producers from consumers, enabling asynchronous processing, load leveling, and resilient architectures.',
                'key_points' => json_encode(['Producer-consumer pattern', 'At-least-once delivery', 'Exactly-once semantics', 'Dead letter queues', 'Ordering guarantees']),
            ],
            [
                'slug' => 'rest',
                'title' => 'REST',
                'category' => 'API Protocols',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "Many developers think REST just means 'use HTTP with JSON.' But REST has specific architectural constraints. Can you name at least 4 REST constraints and explain why a 'REST API' that uses server-side sessions isn't truly RESTful?",
                'description' => 'REST (Representational State Transfer) is an architectural style for designing networked applications, built on HTTP with specific constraints that enable scalability.',
                'key_points' => json_encode(['Statelessness', 'Uniform interface', 'HATEOAS', 'Resource-based URLs', 'HTTP methods and status codes']),
            ],
            [
                'slug' => 'microservices',
                'title' => 'Microservices',
                'category' => 'Application Layer',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "A monolithic e-commerce app is being split into microservices. The team wants services for: Users, Products, Orders, Payments, Notifications. An order requires data from Users, Products, AND Payments. How do you handle this? What new problems does this create?",
                'description' => 'Microservices decompose an application into small, independent services that communicate over the network. They enable team autonomy and independent deployment but introduce distributed systems complexity.',
                'key_points' => json_encode(['Service boundaries', 'Inter-service communication', 'Data ownership', 'Distributed transactions', 'Operational complexity']),
            ],
            [
                'slug' => 'circuit-breaker',
                'title' => 'Circuit Breaker',
                'category' => 'High Availability Patterns',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "Service A calls Service B, which is slow and timing out. Without protection, Service A's threads all block waiting for B, and now A is also down. This is cascading failure. How does a circuit breaker prevent this? Describe its three states.",
                'description' => 'The circuit breaker pattern prevents cascading failures by detecting when a downstream service is failing and short-circuiting requests instead of waiting for timeouts.',
                'key_points' => json_encode(['Closed, Open, Half-Open states', 'Failure threshold', 'Timeout configuration', 'Fallback mechanisms', 'Cascading failure prevention']),
            ],
            [
                'slug' => 'idempotent-operations',
                'title' => 'Idempotent Operations',
                'category' => 'Idempotency',
                'section' => 'core',
                'level' => 'Intermediate',
                'hook_question' => "A user clicks 'Pay \$100' and the request times out. Did the payment go through? The user clicks again. If your API isn't idempotent, they might be charged \$200. How would you design an idempotent payment API?",
                'description' => 'An idempotent operation produces the same result whether executed once or multiple times. This is critical for reliable systems, especially with retries and network failures.',
                'key_points' => json_encode(['Idempotency keys', 'Natural idempotency (GET, PUT, DELETE)', 'Making POST idempotent', 'Retry safety', 'Distributed idempotency']),
            ],
            // ==================== ADVANCED TOPICS (27) ====================
            [
                'slug' => 'layer-7-load-balancing',
                'title' => 'Layer 7 Load Balancing',
                'category' => 'Load Balancers',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "Layer 4 load balancers route based on IP/port. Layer 7 can inspect HTTP headers, cookies, and URL paths. Design a routing scheme where /api/* goes to backend servers, /static/* goes to a CDN, and requests with a 'premium-user' cookie get routed to faster servers.",
                'description' => 'Layer 7 (application layer) load balancers can make routing decisions based on the content of the request, enabling sophisticated traffic management.',
                'key_points' => json_encode(['Content-based routing', 'SSL termination', 'Request manipulation', 'Websocket support', 'Higher overhead vs L4']),
            ],
            [
                'slug' => 'cdn-overview',
                'title' => 'CDN Overview',
                'category' => 'Content Delivery Networks',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "A user in Tokyo accesses your website hosted in Virginia. The round-trip latency is 200ms. How does a CDN reduce this? What content should go on a CDN vs. what shouldn't? What's the difference between push and pull CDNs?",
                'description' => 'CDNs cache content at edge locations worldwide, reducing latency by serving content from the nearest point of presence to the user.',
                'key_points' => json_encode(['Edge locations / PoPs', 'Push vs Pull CDN', 'Cache headers', 'Origin shielding', 'Dynamic content acceleration']),
            ],
            [
                'slug' => 'api-gateway',
                'title' => 'API Gateway',
                'category' => 'General',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "Your microservices architecture has 20 services. Mobile clients need to call 5 of them to load one screen. Should the client make 5 separate calls? How does an API gateway solve this, and what other cross-cutting concerns can it handle?",
                'description' => 'An API gateway is a single entry point for all client requests, providing routing, composition, authentication, rate limiting, and protocol translation.',
                'key_points' => json_encode(['Request routing', 'API composition', 'Authentication/Authorization', 'Protocol translation', 'Request/response transformation']),
            ],
            [
                'slug' => 'cache-eviction-policies',
                'title' => 'Cache Eviction Policies',
                'category' => 'General',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "Your cache is full and a new item needs to be stored. Which existing item do you remove? LRU seems obvious, but Netflix found that LRU performed poorly for their use case. Why might that be, and what alternatives exist?",
                'description' => 'Cache eviction policies determine which items to remove when the cache is full. The right policy depends on your access patterns.',
                'key_points' => json_encode(['LRU (Least Recently Used)', 'LFU (Least Frequently Used)', 'FIFO', 'Random eviction', 'ARC (Adaptive Replacement Cache)']),
            ],
            [
                'slug' => 'database-indexing-strategies',
                'title' => 'Database Indexing Strategies',
                'category' => 'General',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "A query on a 100 million row table takes 30 seconds. You add an index and it drops to 5ms. But now your writes are 3x slower. What's happening under the hood? When would you choose a B-tree index vs. a hash index vs. a full-text index?",
                'description' => 'Database indexes are data structures that speed up reads at the cost of write performance and storage. Choosing the right index strategy is critical for performance.',
                'key_points' => json_encode(['B-tree indexes', 'Hash indexes', 'Composite indexes', 'Covering indexes', 'Index selectivity']),
            ],
            [
                'slug' => 'replication-rdbms',
                'title' => 'Replication (RDBMS)',
                'category' => 'General',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "You need to replicate a PostgreSQL database across 3 data centers. Synchronous replication ensures no data loss but adds latency. Asynchronous replication is fast but can lose data. Is there a middle ground? Describe the tradeoffs.",
                'description' => 'RDBMS replication strategies range from synchronous to asynchronous, each with different consistency, availability, and performance characteristics.',
                'key_points' => json_encode(['Synchronous vs semi-synchronous', 'Statement vs row-based replication', 'WAL shipping', 'Logical replication', 'Multi-master conflicts']),
            ],
            [
                'slug' => 'key-value-store',
                'title' => 'Key-Value Store',
                'category' => 'NoSQL Databases',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "Design a distributed key-value store that can handle 1 million reads/second with <1ms latency. How would you partition the data? How would you handle a node failure? What consistency model would you choose and why?",
                'description' => "Key-value stores are the simplest NoSQL databases, optimized for fast lookups by key. They're the backbone of caching layers and session stores.",
                'key_points' => json_encode(['Partitioning strategies', 'Replication for fault tolerance', 'Consistency models', 'Memory vs disk storage', 'DynamoDB / Redis / etcd']),
            ],
            [
                'slug' => 'distributed-locking',
                'title' => 'Distributed Locking',
                'category' => 'General',
                'section' => 'advanced',
                'level' => 'Advanced',
                'hook_question' => "Two servers both try to process the same job simultaneously. You need a distributed lock. You try using Redis SETNX. But what if the server holding the lock crashes? You add a TTL. But what if the lock holder takes longer than the TTL? Describe the Redlock algorithm.",
                'description' => "Distributed locking coordinates access to shared resources across multiple nodes. It's deceptively difficult to get right due to network partitions and clock skew.",
                'key_points' => json_encode(['Redlock algorithm', 'Fencing tokens', 'Clock skew issues', 'Lock contention', 'ZooKeeper vs Redis vs etcd']),
            ],
            [
                'slug' => 'distributed-transactions-2pc',
                'title' => 'Distributed Transactions (2PC)',
                'category' => 'General',
                'section' => 'advanced',
                'level' => 'Advanced',
                'hook_question' => "An order service needs to deduct inventory AND charge payment atomically. If either fails, both should roll back. But they're separate services with separate databases. How does Two-Phase Commit (2PC) solve this? What's its biggest weakness?",
                'description' => 'Distributed transactions ensure atomicity across multiple services/databases. 2PC is the classic solution but has significant drawbacks in distributed systems.',
                'key_points' => json_encode(['Prepare and Commit phases', 'Coordinator role', 'Blocking problem', 'Saga pattern alternative', 'Eventual consistency approach']),
            ],
            [
                'slug' => 'publisher-subscriber',
                'title' => 'Publisher/Subscriber',
                'category' => 'Messaging Patterns',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "In a request-reply model, the sender must know about the receiver. In pub/sub, publishers don't know who's listening. A user signs up and needs: welcome email, analytics event, CRM update. How does pub/sub make this extensible? What are the delivery guarantees?",
                'description' => "Pub/Sub decouples message producers from consumers through topics/channels. Publishers emit events without knowing who consumes them.",
                'key_points' => json_encode(['Topic-based routing', 'Fan-out pattern', 'At-least-once vs at-most-once', 'Message ordering', 'Kafka, RabbitMQ, SNS/SQS']),
            ],
            [
                'slug' => 'back-pressure',
                'title' => 'Back Pressure',
                'category' => 'Asynchronism Fundamentals',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "Your producer generates 10,000 messages/second but your consumer can only process 2,000/second. The queue grows infinitely until memory runs out and everything crashes. How does back pressure prevent this? Describe at least 3 back pressure strategies.",
                'description' => 'Back pressure is a mechanism for consumers to signal producers to slow down when overwhelmed, preventing unbounded queue growth and system collapse.',
                'key_points' => json_encode(['Flow control', 'Bounded queues', 'Drop strategies', 'Rate-based back pressure', 'Credit-based flow control']),
            ],
            [
                'slug' => 'long-polling-websockets-sse',
                'title' => 'Long Polling, WebSockets & SSE',
                'category' => 'General',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "You're building a real-time chat app. Regular HTTP requires the client to keep asking 'any new messages?' (polling). Compare long polling, WebSockets, and Server-Sent Events. Which would you choose for: chat, live sports scores, and stock prices?",
                'description' => 'Real-time communication patterns go beyond request-response HTTP. Each approach has different tradeoffs for latency, complexity, and resource usage.',
                'key_points' => json_encode(['Short polling overhead', 'Long polling mechanics', 'WebSocket full-duplex', 'SSE one-directional', 'Connection management at scale']),
            ],
            [
                'slug' => 'graphql',
                'title' => 'GraphQL',
                'category' => 'API Protocols',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "A REST API returns a user object with 50 fields, but the mobile app only needs 3 of them. The desktop app needs 20 fields plus related posts. How does GraphQL solve over-fetching and under-fetching? What new problems does it introduce?",
                'description' => "GraphQL lets clients request exactly the data they need in a single query. It solves REST's over-fetching and under-fetching but adds complexity.",
                'key_points' => json_encode(['Schema definition language', 'Resolvers', 'N+1 query problem', 'Batching with DataLoader', 'Caching challenges']),
            ],
            [
                'slug' => 'grpc',
                'title' => 'gRPC',
                'category' => 'API Protocols',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => 'REST uses JSON over HTTP/1.1 for most implementations. gRPC uses Protocol Buffers over HTTP/2. In benchmarks, gRPC is often 7-10x faster. Why? When would you still choose REST over gRPC?',
                'description' => 'gRPC is a high-performance RPC framework that uses Protocol Buffers for serialization and HTTP/2 for transport, ideal for service-to-service communication.',
                'key_points' => json_encode(['Protocol Buffers', 'HTTP/2 multiplexing', 'Streaming support', 'Code generation', 'Browser limitations']),
            ],
            [
                'slug' => 'backends-for-frontend-bff',
                'title' => 'Backends for Frontend (BFF)',
                'category' => 'Design & Implementation Patterns',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "Your API serves both a mobile app (needs minimal data, slow network) and a web dashboard (needs rich data, fast network). One API can't serve both well. How does the BFF pattern solve this? How is it different from an API gateway?",
                'description' => "The BFF pattern creates dedicated backend services for each frontend type, optimizing the API for each client's specific needs.",
                'key_points' => json_encode(['Per-client optimization', 'Reduced over-fetching', 'Team ownership alignment', 'Gateway vs BFF distinction', 'Duplication tradeoffs']),
            ],
            [
                'slug' => 'service-discovery',
                'title' => 'Service Discovery',
                'category' => 'Application Layer',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "In microservices, Service A needs to call Service B. But Service B has 10 instances and their IPs change as containers scale up/down. Hardcoding IPs won't work. How does service discovery solve this? Compare client-side vs server-side discovery.",
                'description' => 'Service discovery automatically detects network locations of service instances, essential in dynamic environments where instances are constantly created and destroyed.',
                'key_points' => json_encode(['Service registry', 'Client-side discovery', 'Server-side discovery', 'Health checking', 'Consul, Eureka, Kubernetes DNS']),
            ],
            [
                'slug' => 'strangler-fig',
                'title' => 'Strangler Fig',
                'category' => 'Design & Implementation Patterns',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "You have a 10-year-old monolith that's impossible to rewrite from scratch — it would take years and the business can't wait. How do you incrementally migrate to microservices without a 'big bang' rewrite? Describe the Strangler Fig pattern step by step.",
                'description' => 'The Strangler Fig pattern incrementally replaces a legacy system by gradually routing traffic from old to new implementations, like a fig vine growing around a tree.',
                'key_points' => json_encode(['Incremental migration', 'Facade/proxy layer', 'Feature-by-feature replacement', 'Rollback safety', 'Parallel running']),
            ],
            [
                'slug' => 'sidecar-pattern',
                'title' => 'Sidecar Pattern',
                'category' => 'Design & Implementation Patterns',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "Every microservice needs logging, monitoring, TLS, and retry logic. Implementing these in each service (written in different languages) is duplicative. How does the sidecar pattern solve this? How does a service mesh (like Istio) use sidecars?",
                'description' => 'The sidecar pattern deploys helper processes alongside application containers, handling cross-cutting concerns like networking, observability, and security.',
                'key_points' => json_encode(['Co-located process', 'Language-agnostic infrastructure', 'Service mesh (Envoy/Istio)', 'Resource overhead', 'Separation of concerns']),
            ],
            [
                'slug' => 'retry-pattern',
                'title' => 'Retry Pattern',
                'category' => 'Resiliency Patterns',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "A service call fails due to a transient network error. You add retry logic: retry 3 times with 1 second delay. But now when the downstream service is overloaded, your retries make it worse — a 'retry storm.' How do you implement retries safely?",
                'description' => 'The retry pattern handles transient failures by re-attempting failed operations. Done wrong, retries can amplify failures instead of recovering from them.',
                'key_points' => json_encode(['Exponential backoff', 'Jitter', 'Retry budgets', 'Idempotency requirement', 'Circuit breaker integration']),
            ],
            [
                'slug' => 'bulkhead-pattern',
                'title' => 'Bulkhead Pattern',
                'category' => 'High Availability Patterns',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "Your service has one thread pool handling all requests. When the 'recommendations' downstream service becomes slow, all threads are stuck waiting for it, and even 'checkout' requests (which don't need recommendations) start failing. How does the bulkhead pattern fix this?",
                'description' => "The bulkhead pattern isolates components so that failure in one doesn't cascade to others — like watertight compartments in a ship.",
                'key_points' => json_encode(['Thread pool isolation', 'Connection pool isolation', 'Semaphore isolation', 'Failure containment', 'Resource partitioning']),
            ],
            [
                'slug' => 'cqrs',
                'title' => 'CQRS',
                'category' => 'Data Management Patterns',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "Your e-commerce database handles both complex analytical queries (dashboard) and simple transactional writes (orders). The reads are slow because the write-optimized schema isn't good for reads. How does CQRS solve this? What's the consistency tradeoff?",
                'description' => 'Command Query Responsibility Segregation separates read and write models, allowing each to be optimized independently for their specific access patterns.',
                'key_points' => json_encode(['Separate read/write models', 'Event-driven synchronization', 'Eventual consistency between models', 'Read optimization', 'Write optimization']),
            ],
            [
                'slug' => 'event-sourcing',
                'title' => 'Event Sourcing',
                'category' => 'Data Management Patterns',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "Traditional databases store current state: 'account balance = \$500.' Event sourcing stores every change: 'deposited \$100, withdrew \$50, deposited \$450.' What advantages does this give you? How do you efficiently query the current balance from millions of events?",
                'description' => 'Event sourcing stores all changes as a sequence of immutable events, providing a complete audit trail and enabling temporal queries and event replay.',
                'key_points' => json_encode(['Immutable event log', 'Event replay', 'Snapshots for performance', 'CQRS synergy', 'Audit trail and debugging']),
            ],
            [
                'slug' => 'monitoring-overview',
                'title' => 'Monitoring Overview',
                'category' => 'Monitoring',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "Your service is running in production. How do you know if it's healthy? The four golden signals of monitoring are latency, traffic, errors, and saturation. Explain each and describe what thresholds you'd alert on for a payment service.",
                'description' => 'Monitoring collects, processes, and alerts on system metrics and logs. Effective monitoring is the foundation of reliable operations.',
                'key_points' => json_encode(['Four golden signals', 'Metrics vs logs vs traces', 'Alerting strategies', 'Dashboards', 'Prometheus, Grafana, ELK stack']),
            ],
            [
                'slug' => 'n-plus-1-query-problem',
                'title' => 'N+1 Query Problem',
                'category' => 'Performance Antipatterns',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => "You load a list of 100 blog posts, then for each post you make a separate database query to get the author. That's 101 queries total. With each query taking 5ms, that's 505ms. How would you reduce this to just 2 queries? How does this manifest in ORMs?",
                'description' => 'The N+1 query problem occurs when code executes N additional queries to fetch related data for N records, instead of fetching everything in a single optimized query.',
                'key_points' => json_encode(['Eager loading', 'JOIN queries', 'Batch fetching', 'DataLoader pattern', 'ORM detection tools']),
            ],
            [
                'slug' => 'performance-antipatterns-overview',
                'title' => 'Performance Antipatterns Overview',
                'category' => 'Performance Antipatterns',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => 'Name 5 common performance antipatterns in distributed systems. For each, explain why developers fall into them and what the fix is. Think about database access, service communication, caching, and data serialization.',
                'description' => 'Performance antipatterns are common design mistakes that degrade system performance. Recognizing them is as important as knowing the correct patterns.',
                'key_points' => json_encode(['Chatty I/O', 'Synchronous I/O in critical paths', 'Improper caching', 'No pagination', 'Monolithic database access']),
            ],
            [
                'slug' => 'search-systems-inverted-index',
                'title' => 'Search Systems & Inverted Index',
                'category' => 'General',
                'section' => 'advanced',
                'level' => 'Intermediate',
                'hook_question' => 'Google searches billions of web pages in under a second. Regular database LIKE queries would take hours. What data structure makes this possible? Explain how an inverted index works and how search engines rank results.',
                'description' => 'Search systems use inverted indexes to enable fast full-text search across massive datasets. Understanding this is essential for building search features.',
                'key_points' => json_encode(['Inverted index structure', 'Tokenization and stemming', 'TF-IDF scoring', 'Elasticsearch/Solr', 'Sharding search indexes']),
            ],
            [
                'slug' => 'stream-processing',
                'title' => 'Stream Processing',
                'category' => 'General',
                'section' => 'advanced',
                'level' => 'Advanced',
                'hook_question' => 'You need to detect fraudulent credit card transactions within 5 seconds of them occurring. Batch processing (running every hour) is too slow. How does stream processing handle this? Compare Apache Kafka Streams, Apache Flink, and Apache Spark Streaming.',
                'description' => 'Stream processing handles continuous data flows in real-time, enabling near-instant reactions to events rather than periodic batch processing.',
                'key_points' => json_encode(['Event time vs processing time', 'Windowing strategies', 'Exactly-once processing', 'State management', 'Kafka Streams, Flink, Spark Streaming']),
            ],
        ];
    }
}
